"""Generate a lock file with the exact ML-dependency versions installed right now.

requirements-v1.5.txt and requirements-challenger-v1.txt only pin floor (and,
since this script was added, ceiling) versions - they describe a *range* of
versions pip is allowed to resolve, not the exact versions that were actually
tested. Two machines installing from the same requirements files on different
days can end up with different pandas/numpy/scikit-learn patch releases, and a
behavioral difference between those releases is exactly what caused the
_fold_blocks purge-window bug.

Run this once after installing (`pip install -r requirements-v1.5.txt -r
requirements-challenger-v1.txt`) to record the exact versions that were
actually used for a known-good training run:

    python scripts/freeze_requirements.py

It writes requirements-v1.5.lock.txt next to the ranged requirements files.
Re-run it after any deliberate upgrade; commit the updated lock file so the
next environment (or a teammate) can reproduce the same versions with:

    pip install -r requirements-v1.5.lock.txt
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TRACKED = {"pandas", "numpy", "requests", "python-dotenv", "pyarrow", "scikit-learn"}


def _installed_versions() -> dict[str, str]:
    out = subprocess.run(
        [sys.executable, "-m", "pip", "freeze"],
        check=True, capture_output=True, text=True,
    ).stdout
    versions: dict[str, str] = {}
    for line in out.splitlines():
        line = line.strip()
        if "==" not in line:
            continue
        name, _, version = line.partition("==")
        versions[name.lower()] = version
    return versions


def main() -> int:
    versions = _installed_versions()
    missing = sorted(pkg for pkg in TRACKED if pkg not in versions)
    if missing:
        print("[VIRHE] seuraavat paketit eivat ole asennettuna, joten lock-tiedostoa "
              "ei kirjoiteta:", ", ".join(missing))
        print("Aja ensin: pip install -r requirements-v1.5.txt -r requirements-challenger-v1.txt")
        return 1

    lock_path = ROOT / "requirements-v1.5.lock.txt"
    lines = [
        "# Generated by scripts/freeze_requirements.py - exact versions from a",
        "# known-good install, not a range. Re-run the script after an intentional",
        "# upgrade instead of hand-editing this file.",
    ]
    for pkg in sorted(TRACKED):
        lines.append(f"{pkg}=={versions[pkg]}")
    lock_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[OK] Kirjoitettiin {lock_path} ({len(TRACKED)} pakettia).")
    for pkg in sorted(TRACKED):
        print(f"  {pkg}=={versions[pkg]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
